# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Polygonizer
                                 A QGIS plugin
 A plugin to help make Vision Zero Polygons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-27
        copyright            : (C) 2023 by DTS
        email                : frank.hereford@austintexas.gov
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Polygonizer class from file Polygonizer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .polygonizer import Polygonizer
    return Polygonizer(iface)
